---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-synchroniser-account
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rbac-synchroniser-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  - clusterrolebindings
  - clusterroles
  verbs: ["*"]
  resourceNames:
  - sync-test

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rbac-synchroniser-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-synchroniser-role
subjects:
- kind: ServiceAccount
  name: rbac-synchroniser-account
  namespace: kube-system

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rbac-synchroniser
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: rbac-synchroniser
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
      labels:
        app: rbac-synchroniser
    spec:
      serviceAccountName: rbac-synchroniser-account
      containers:
      - name: rbac-synchroniser
        image: quay.io/google-cloud-tools/kubernetes-rbac-synchroniser
        imagePullPolicy: Always
        # Sync the "sync-fake@example.com" Google Group
        # with the "sync-test" rolebinding and the "sync-test" cluster role
        # in "default" namespace
        args:
        - '-update-interval=15m'
        - '-cluster-role-name=sync-test'
        - '-rolebinding-name=sync-test'
        - '-fake-group-response'
        - '-namespace-group=default:sync-fake@test.com'
        # - '-google-admin-email=admin@example.com'
        # - '-config-file-path=/secrets/credentials.json'
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
            requests:
                cpu: 0
                memory: 10Mi
            limits:
                cpu: 0.1
                memory: 50Mi
      #   volumeMounts:
      #     - name: google-admin-api-credentials
      #       mountPath: /secrets
      #       readOnly: true
      # volumes:
      #   - name: google-admin-api-credentials
      #     secret:
      #       secretName: google-admin-api-credentials
      #       items:
      #         - key: credentials.json
      #           path: credentials.json
